### ISSUE TITLE
Cannot find module 'redial'

### ISSUE THREAD

**Issue by DWboutin** [dlmr/react-router-redial#14]
I just installed it and it makes this error. Maybe it should be installed when we run `npm install react-router-redial`? I solve my problem by installing it manually.

```sh
Error: Cannot find module 'redial'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Mike/Desktop/react-webpack-startup/node_modules/react-router-redial/lib/triggerHooks.js:11:15)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Mike/Desktop/react-webpack-startup/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

**Comment by dlmr** [comment]
Hello! 

`redial` is not included by default, the reason for the error you get, but a part of [`peerDependencies`](https://docs.npmjs.com/files/package.json#peerdependencies). Maybe we should update the README to make this more clear?

So if you already have React and React Router in your project you will need to do the following to get everything you need:

```
npm install --save react-router-redial redial
```

**Comment by DWboutin** [comment]
It didn't bothered me a lot, but when i install a package, it is fully ready with it's dependencies.

**Comment by PAkerstrand** [comment]
@DWboutin: while I understand that it can be confusing/annoying, using `peerDependencies` allows us to work with multiple versions of `redial` and let the client decide which of the compatible versions to use. This avoids more subtle bugs such as having multiple versions of redial where the `Symbol` would differ and thus not trigger any hooks

**Comment by DWboutin** [comment]
With your add to the Read.me, it's perfect for me and future users!

Thank you and great package btw!
